services:
  nao_driver:
    build: .
    network_mode: host
    ipc: host
    env_file:
      - .env
    command: >
      bash -c 'source /opt/ros/humble/setup.bash && source /ws/install/setup.bash
      && ros2 run naoqi_driver naoqi_driver_node --ros-args
      -p nao_ip:=${NAO_IP}
      -p nao_port:=9559
      -p user:=${NAO_USERNAME}
      -p password:=${NAO_PASSWORD}'

  ros_bridge:
    build: .
    network_mode: host
    env_file:
      - .env
    command: >
      bash -c 'source /opt/ros/humble/setup.bash && source /ws/install/setup.bash
      && ros2 run rosbridge_server rosbridge_websocket --ros-args -p port:=${BRIDGE_PORT}'

  ros_api:
    build: .
    network_mode: host
    command: >
      bash -c 'source /opt/ros/humble/setup.bash && source /ws/install/setup.bash
      && ros2 run rosapi rosapi_node'
